### ISSUE TITLE
workflow fails with Nextflow 24.04.1

### ISSUE THREAD

**Issue by angelovangel** [epi2me-labs/wf-clone-validation#47]
### Operating System

macOS

### Workflow Version

1.2.0

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### What happened?

The pipeline fails to start after updating nextflow to 24.04.1
It runs OK with `NXF_VER=23.04.3`

```
ERROR ~ Script compilation error
- file : /Users/angelangelov/.nextflow/assets/epi2me-labs/wf-clone-validation/main.nf
- cause: Invalid output definition @ line 652, column 5.
       output(results[0])
       ^

1 error


 -- Check '.nextflow.log' file for details
```

### Relevant log output

```shell
May-27 08:18:52.998 [main] ERROR nextflow.cli.Launcher - Script compilation error
- file : /Users/angelangelov/.nextflow/assets/epi2me-labs/wf-clone-validation/main.nf
- cause: Invalid output definition @ line 652, column 5.
       output(results[0])
       ^
```
```


### Application activity log entry

_No response_

### Were you able to successfully run the latest version of the workflow with the demo data?

no

### Other demo data information

_No response_

**Comment by sarahjeeeze** [comment]
Thanks for letting us know, we will update this soon. For now if you could stick with  NXF_VER=23.04.3 that would be great

**Comment by cjw85** [comment]
@ryandward You are correct. Nextflow 24.04 has introduced new keywords into the Nextflow DSL grammar. These conflict with the use of `output` as a process name (in some contexts). In essence we need to rename the `output` process in the workflow to something else.

**Comment by sarahjeeeze** [comment]
This has been fixed
